// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQwwL7bqyEM42pg4056Sbz_Q73vOGbCSU',
    appId: '1:841808922624:android:2aee4da19d3a02491870e5',
    messagingSenderId: '841808922624',
    projectId: 'edufinder-1ad73',
    storageBucket: 'edufinder-1ad73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8q1uN_MnBaFSRKM4ur7_71I3ANDOxOxM',
    appId: '1:841808922624:ios:56c9e6f7eb6fdcff1870e5',
    messagingSenderId: '841808922624',
    projectId: 'edufinder-1ad73',
    storageBucket: 'edufinder-1ad73.firebasestorage.app',
    iosBundleId: 'com.example.edufindr',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoSsb_GqCLUDmtKBmf-94ay8cGnnM45Ek',
    appId: '1:841808922624:web:0edff00ce6f1cd611870e5',
    messagingSenderId: '841808922624',
    projectId: 'edufinder-1ad73',
    authDomain: 'edufinder-1ad73.firebaseapp.com',
    storageBucket: 'edufinder-1ad73.firebasestorage.app',
    measurementId: 'G-1VH5YK2NPS',
  );

}